[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Saros"
authors = [{name = "Asami Umbra", email = "asamiumbra@gmail.com"}]
dynamic = ["version", "description"]
